### ISSUE TITLE
Switch Ansible calls to objects

### ISSUE THREAD

**Issue by andrewvaughan** [andrewvaughan/devops#11]
Instead of using something like this:

```yaml
- name: "Installing Docker"
   apt: >
     name=docker-engine
     state=latest
```

Use this:

```yaml
- name: "Installing Docker"
   apt:
     name  : docker-engine
     state : latest
```
